# api/services/topics.py
# 500 sujets de philosophie et société pour l'entraînement

TOPICS = {
    "Philosophie": [
        "La liberté est-elle une illusion ?",
        "Peut-on être heureux sans être libre ?",
        "La mort donne-t-elle un sens à la vie ?",
        "L'homme est-il naturellement bon ou mauvais ?",
        "Peut-on vivre sans croire en quelque chose ?",
        "Le bonheur est-il le but de la vie ?",
        "La raison suffit-elle à guider nos actions ?",
        "Faut-il craindre la mort ?",
        "L'art est-il nécessaire à l'homme ?",
        "La conscience fait-elle de l'homme un être à part ?",
        "Peut-on tout expliquer par la science ?",
        "La vérité existe-t-elle ?",
        "Sommes-nous responsables de ce que nous sommes ?",
        "Le temps est-il notre ennemi ?",
        "Peut-on vivre sans illusions ?",
        "L'amour est-il une forme de folie ?",
        "Faut-il obéir aux lois injustes ?",
        "La souffrance a-t-elle un sens ?",
        "L'identité se choisit-elle ?",
        "Peut-on se connaître soi-même ?",
        "Le désir est-il source de malheur ?",
        "La vie a-t-elle un sens objectif ?",
        "Faut-il toujours dire la vérité ?",
        "L'homme peut-il se passer de la philosophie ?",
        "Le travail est-il une valeur ?",
        "Peut-on être moral sans religion ?",
        "L'imagination est-elle dangereuse ?",
        "La beauté est-elle objective ?",
        "Faut-il avoir peur de l'avenir ?",
        "Le progrès est-il toujours une bonne chose ?",
        "Peut-on vivre sans projet ?",
        "L'ennui est-il un luxe ?",
        "Faut-il respecter la tradition ?",
        "La mémoire est-elle identité ?",
        "Peut-on être juste sans être bon ?",
        "Le corps est-il un obstacle à la pensée ?",
        "Faut-il craindre le changement ?",
        "L'amitié est-elle possible entre inégaux ?",
        "La sagesse s'apprend-elle ?",
        "Peut-on vivre sans espoir ?",
    ],
    "Société & Politique": [
        "La démocratie est-elle le meilleur régime ?",
        "Faut-il limiter la liberté d'expression ?",
        "L'égalité est-elle compatible avec la liberté ?",
        "Le capitalisme peut-il être réformé ?",
        "La mondialisation est-elle une chance ?",
        "Faut-il abolir la peine de mort ?",
        "L'État doit-il contrôler internet ?",
        "La violence est-elle parfois légitime ?",
        "Faut-il voter de façon obligatoire ?",
        "Le service militaire doit-il être universel ?",
        "Les frontières ont-elles encore un sens ?",
        "La laïcité est-elle menacée ?",
        "Faut-il légaliser toutes les drogues ?",
        "Le revenu universel est-il une utopie ?",
        "La surveillance de masse est-elle justifiable ?",
        "Faut-il instaurer des quotas de parité ?",
        "L'immigration est-elle une richesse ?",
        "Le vote blanc doit-il être comptabilisé ?",
        "Faut-il taxer davantage les riches ?",
        "La liberté de la presse est-elle absolue ?",
        "Le populisme est-il une menace pour la démocratie ?",
        "Faut-il un gouvernement mondial ?",
        "Les réseaux sociaux renforcent-ils la démocratie ?",
        "Le lobbying est-il une forme de corruption ?",
        "Faut-il abaisser l'âge du droit de vote ?",
        "La désobéissance civile est-elle légitime ?",
        "Peut-on être patriote et citoyen du monde ?",
        "Les riches ont-ils trop de pouvoir ?",
        "Faut-il remettre en question le droit de propriété ?",
        "La politique est-elle affaire de spécialistes ?",
        "Faut-il interdire les partis extrémistes ?",
        "L'anarchie est-elle possible ?",
        "La justice sociale existe-t-elle ?",
        "Faut-il réformer l'ONU ?",
        "Le nationalisme est-il dangereux ?",
        "Les médias sont-ils indépendants ?",
        "Faut-il réglementer les GAFA ?",
        "La démocratie représentative est-elle dépassée ?",
        "Faut-il un revenu minimum universel ?",
        "La fin justifie-t-elle les moyens en politique ?",
    ],
    "Technologie & IA": [
        "L'intelligence artificielle va-t-elle détruire l'emploi ?",
        "Faut-il réguler le développement de l'IA ?",
        "La technologie nous rend-elle plus humains ?",
        "Les réseaux sociaux sont-ils dangereux pour la démocratie ?",
        "Peut-on faire confiance aux algorithmes ?",
        "Le transhumanisme est-il une menace ?",
        "Internet a-t-il tué la vie privée ?",
        "Les robots doivent-ils avoir des droits ?",
        "L'IA peut-elle être créative ?",
        "Faut-il interdire les deepfakes ?",
        "Le télétravail est-il l'avenir du travail ?",
        "La dépendance au smartphone est-elle une maladie ?",
        "Les données personnelles sont-elles une monnaie ?",
        "Faut-il instaurer un droit à la déconnexion ?",
        "L'IA peut-elle remplacer un juge ?",
        "Le métavers est-il une fuite de la réalité ?",
        "Faut-il taxer les robots ?",
        "La vie numérique est-elle une vraie vie ?",
        "L'IA va-t-elle surpasser l'intelligence humaine ?",
        "Les cyberattaques sont-elles la guerre du futur ?",
        "Faut-il enseigner le code à l'école ?",
        "La voiture autonome est-elle éthique ?",
        "Les GAFA sont-ils plus puissants que les États ?",
        "Faut-il un passeport numérique mondial ?",
        "L'impression 3D va-t-elle révolutionner l'industrie ?",
        "La blockchain peut-elle transformer la démocratie ?",
        "Faut-il réguler les cryptomonnaies ?",
        "L'IA peut-elle diagnostiquer mieux qu'un médecin ?",
        "Le Big Data est-il une chance ou un danger ?",
        "Faut-il interdire TikTok ?",
        "Les influenceurs sont-ils responsables de leur impact ?",
        "La réalité virtuelle va-t-elle changer l'éducation ?",
        "L'IA doit-elle avoir une conscience morale ?",
        "Faut-il un impôt mondial sur le numérique ?",
        "Les jeux vidéo sont-ils une forme d'art ?",
        "La désinformation en ligne peut-elle être combattue ?",
        "Faut-il une déclaration des droits numériques ?",
        "L'automatisation va-t-elle créer plus d'emplois qu'elle n'en détruit ?",
        "Le droit à l'oubli numérique est-il réalisable ?",
        "L'IA peut-elle écrire de la poésie ?",
    ],
    "Environnement & Écologie": [
        "La croissance économique est-elle compatible avec l'écologie ?",
        "Faut-il instaurer un tribunal climatique international ?",
        "L'écotaxe est-elle juste ?",
        "Peut-on être écologiste et capitaliste ?",
        "Faut-il interdire les voitures thermiques ?",
        "L'énergie nucléaire est-elle écologique ?",
        "La viande doit-elle être taxée ?",
        "Faut-il repenser notre rapport à la consommation ?",
        "L'écologie est-elle l'affaire de tous ?",
        "Faut-il un référendum sur le climat ?",
        "La désobéissance civile est-elle justifiée pour le climat ?",
        "Peut-on concilier tourisme et développement durable ?",
        "Faut-il décroître pour sauver la planète ?",
        "Les animaux ont-ils des droits ?",
        "Faut-il végétaliser les villes ?",
        "L'eau sera-t-elle l'or bleu du XXIe siècle ?",
        "Faut-il une taxe carbone mondiale ?",
        "La fast fashion doit-elle être interdite ?",
        "Peut-on voyager en avion et être écologiste ?",
        "L'agriculture intensive est-elle condamnable ?",
        "Faut-il rendre le recyclage obligatoire ?",
        "Le véganisme est-il une solution ou une utopie ?",
        "Faut-il protéger les forêts comme des personnes juridiques ?",
        "Les océans sont-ils condamnés ?",
        "Faut-il enseigner l'écologie à l'école primaire ?",
        "La géo-ingénierie est-elle une solution au réchauffement ?",
        "Peut-on être optimiste face au changement climatique ?",
        "Faut-il interdire les plastiques à usage unique ?",
        "L'écologie est-elle de gauche ?",
        "Faut-il indemniser les pays pauvres pour le changement climatique ?",
        "Le développement durable est-il une contradiction ?",
        "Faut-il taxer les jets privés ?",
        "L'énergie solaire peut-elle remplacer le pétrole ?",
        "Faut-il un service civique écologique ?",
        "La nature a-t-elle une valeur en soi ?",
        "Peut-on nourrir 10 milliards d'humains de façon durable ?",
        "Faut-il interdire la publicité pour les produits polluants ?",
        "L'urbanisation est-elle l'ennemie de la nature ?",
        "Faut-il nationaliser les ressources naturelles ?",
        "Le capitalisme vert est-il possible ?",
    ],
    "Éducation & Culture": [
        "L'école prépare-t-elle à la vie ?",
        "Faut-il supprimer les notes à l'école ?",
        "L'université doit-elle être gratuite ?",
        "La culture est-elle accessible à tous ?",
        "Faut-il enseigner la philosophie dès le primaire ?",
        "Les grandes écoles reproduisent-elles les inégalités ?",
        "L'art peut-il changer le monde ?",
        "Faut-il rendre l'école obligatoire jusqu'à 18 ans ?",
        "La lecture est-elle en danger ?",
        "Le sport est-il un vecteur de valeurs ?",
        "Faut-il enseigner les religions à l'école ?",
        "La culture populaire a-t-elle de la valeur ?",
        "L'éducation nationale est-elle en crise ?",
        "Faut-il interdire les écrans à l'école ?",
        "La mémoire est-elle essentielle à l'apprentissage ?",
        "Faut-il valoriser l'apprentissage autant que le bac ?",
        "L'art contemporain est-il incompréhensible ?",
        "Faut-il financer la culture par l'impôt ?",
        "La langue française est-elle menacée ?",
        "Faut-il enseigner l'éloquence à l'école ?",
        "Les musées doivent-ils restituer les œuvres coloniales ?",
        "Faut-il une éducation émotionnelle à l'école ?",
        "La compétition scolaire est-elle saine ?",
        "Faut-il supprimer le baccalauréat ?",
        "L'éducation peut-elle éradiquer le racisme ?",
        "Le cinéma est-il un art mineur ?",
        "Faut-il davantage de mixité sociale dans les écoles ?",
        "L'histoire doit-elle être objective ?",
        "Faut-il enseigner le féminisme à l'école ?",
        "La curiosité s'enseigne-t-elle ?",
        "Faut-il rémunérer les étudiants ?",
        "L'école peut-elle rendre heureux ?",
        "Faut-il des classes séparées selon le niveau ?",
        "La culture générale est-elle utile ?",
        "Faut-il obligatoirement passer par l'école pour réussir ?",
        "Les langues régionales méritent-elles d'être enseignées ?",
        "L'éducation à l'image est-elle urgente ?",
        "Faut-il des devoirs à la maison ?",
        "Le jeu est-il une forme d'apprentissage ?",
        "Faut-il une éducation sexuelle complète à l'école ?",
    ],
    "Économie & Travail": [
        "Le chômage est-il inévitable ?",
        "Faut-il réduire le temps de travail ?",
        "La semaine de 4 jours est-elle l'avenir ?",
        "Le travail est-il une valeur fondamentale ?",
        "Faut-il un salaire maximum ?",
        "L'entrepreneuriat est-il accessible à tous ?",
        "La finance est-elle utile à la société ?",
        "Faut-il supprimer les paradis fiscaux ?",
        "Le travail du dimanche est-il acceptable ?",
        "La retraite à 60 ans est-elle possible ?",
        "Faut-il instaurer un revenu universel de base ?",
        "Les syndicats sont-ils encore utiles ?",
        "Le libéralisme économique profite-t-il à tous ?",
        "Faut-il nationaliser les grandes entreprises ?",
        "L'inflation est-elle toujours mauvaise ?",
        "Le travail à distance est-il une révolution ?",
        "Faut-il encadrer les salaires des dirigeants ?",
        "La dette publique est-elle un problème ?",
        "L'économie circulaire est-elle viable ?",
        "Faut-il une taxation des héritages ?",
        "La gratuité des transports en commun est-elle réalisable ?",
        "Faut-il une banque publique d'investissement ?",
        "Le travail des enfants existe-t-il encore en France ?",
        "La start-up nation est-elle un mythe ?",
        "Faut-il remettre en cause le libre-échange ?",
        "L'argent fait-il le bonheur ?",
        "Faut-il taxer les robots qui remplacent les humains ?",
        "La croissance verte est-elle possible ?",
        "Faut-il réformer le système bancaire ?",
        "Le tourisme de masse est-il viable ?",
        "Faut-il un salaire minimum européen ?",
        "L'économie collaborative est-elle l'avenir ?",
        "Faut-il remettre en cause la propriété intellectuelle ?",
        "La mondialisation a-t-elle créé plus d'inégalités ?",
        "Le mécénat d'entreprise est-il suffisant pour la culture ?",
        "Faut-il obliger les entreprises à la transparence salariale ?",
        "L'actionnariat salarié est-il une solution ?",
        "Faut-il supprimer les stock-options ?",
        "Le dumping social est-il une forme de concurrence déloyale ?",
        "Faut-il une épargne retraite obligatoire ?",
    ],
    "Éthique & Bioéthique": [
        "La PMA pour toutes est-elle un progrès ?",
        "Faut-il légaliser l'euthanasie ?",
        "Le clonage humain est-il acceptable ?",
        "Faut-il modifier génétiquement les embryons ?",
        "L'avortement est-il un droit absolu ?",
        "Faut-il légaliser le don d'organes présumé ?",
        "Les mères porteuses doivent-elles être rémunérées ?",
        "L'eugénisme positif est-il éthique ?",
        "Faut-il tester les médicaments sur les animaux ?",
        "La recherche sur les cellules souches est-elle acceptable ?",
        "Faut-il limiter la prolongation artificielle de la vie ?",
        "Le secret médical est-il absolu ?",
        "Faut-il rendre la vaccination obligatoire ?",
        "L'accès aux soins est-il un droit universel ?",
        "Peut-on breveter le vivant ?",
        "La médecine prédictive est-elle éthique ?",
        "Faut-il informer un patient d'un diagnostic fatal ?",
        "Le don du sang doit-il être anonyme ?",
        "Faut-il un revenu pour les aidants familiaux ?",
        "La médecine de guerre est-elle une contradiction ?",
        "Peut-on refuser des soins pour raisons religieuses ?",
        "Faut-il remettre en question l'acharnement thérapeutique ?",
        "Les personnes âgées sont-elles bien traitées en France ?",
        "Faut-il une loi sur la fin de vie ?",
        "La santé mentale est-elle suffisamment prise en compte ?",
        "Faut-il dépénaliser le suicide assisté ?",
        "Le prix des médicaments est-il éthique ?",
        "Faut-il un droit à l'enfant ?",
        "La médecine est-elle trop médicalisée ?",
        "Faut-il enseigner l'éthique aux médecins ?",
    ],
    "Justice & Droit": [
        "La prison est-elle efficace ?",
        "Faut-il réformer la justice ?",
        "Les peines planchers sont-elles justes ?",
        "La présomption d'innocence est-elle respectée ?",
        "Faut-il juger les crimes de guerre par un tribunal international ?",
        "La justice est-elle la même pour tous ?",
        "Faut-il une cour pénale internationale plus puissante ?",
        "Le pardon est-il une vertu ou une faiblesse ?",
        "Faut-il légaliser la prostitution ?",
        "La justice restaurative est-elle efficace ?",
        "Faut-il supprimer la Cour d'assises ?",
        "Les jurés populaires sont-ils compétents ?",
        "Faut-il réformer le droit d'asile ?",
        "La prescription des crimes est-elle justifiable ?",
        "Faut-il une police de la déontologie indépendante ?",
        "La récidive prouve-t-elle l'échec de la prison ?",
        "Faut-il décriminaliser certains délits mineurs ?",
        "La justice des mineurs est-elle trop laxiste ?",
        "Faut-il un casier judiciaire effaçable ?",
        "La torture est-elle jamais justifiable ?",
    ],
    "Relations internationales": [
        "La guerre est-elle inévitable ?",
        "L'ONU est-elle encore utile ?",
        "Faut-il armer l'Ukraine ?",
        "Le droit d'ingérence humanitaire est-il légitime ?",
        "La Chine va-t-elle dominer le monde ?",
        "Faut-il un siège permanent européen au Conseil de sécurité ?",
        "Les sanctions économiques sont-elles efficaces ?",
        "Faut-il une armée européenne ?",
        "L'OTAN est-elle dépassée ?",
        "Les pays riches ont-ils une dette envers les pays pauvres ?",
        "Faut-il annuler la dette des pays en développement ?",
        "Le terrorisme peut-il être vaincu ?",
        "Faut-il négocier avec les dictateurs ?",
        "La diplomatie peut-elle tout résoudre ?",
        "Les réfugiés climatiques sont-ils une priorité mondiale ?",
        "Faut-il une taxe sur les transactions financières internationales ?",
        "Le soft power est-il plus efficace que la guerre ?",
        "Faut-il réformer le FMI et la Banque mondiale ?",
        "La décolonisation est-elle terminée ?",
        "Les guerres économiques remplaceront-elles les guerres militaires ?",
    ],
    "Identité & Société": [
        "Le féminisme est-il encore nécessaire ?",
        "Le racisme systémique existe-t-il en France ?",
        "Faut-il écrire en écriture inclusive ?",
        "La cancel culture est-elle un progrès ou une régression ?",
        "Le wokisme est-il une menace pour la liberté ?",
        "Faut-il des espaces non-mixtes ?",
        "L'identité de genre est-elle une construction sociale ?",
        "Le mariage pour tous a-t-il changé la société ?",
        "Faut-il des quotas de diversité dans les entreprises ?",
        "La masculinité est-elle en crise ?",
        "Faut-il repenser la famille traditionnelle ?",
        "Les religions sont-elles compatibles avec la modernité ?",
        "Le voile islamique est-il un signe de liberté ou d'oppression ?",
        "Faut-il enseigner l'histoire coloniale dans les écoles ?",
        "L'humour peut-il tout dire ?",
        "Le féminisme est-il universel ?",
        "Faut-il lutter contre les stéréotypes de genre dès l'enfance ?",
        "La famille homoparentale est-elle différente des autres ?",
        "Faut-il une journée de commémoration de l'esclavage ?",
        "La diversité est-elle une force ?",
        "Le communautarisme est-il un danger pour la République ?",
        "Faut-il supprimer la mention du sexe sur les documents officiels ?",
        "Le patriarcat existe-t-il encore ?",
        "Faut-il enseigner les luttes LGBTQ+ à l'école ?",
        "L'intégration a-t-elle échoué en France ?",
        "Le métissage culturel est-il un enrichissement ?",
        "Faut-il une loi contre les discours de haine en ligne ?",
        "Le port du voile à l'université doit-il être interdit ?",
        "Faut-il des statistiques ethniques en France ?",
        "La France est-elle un pays raciste ?",
    ],
    "Psychologie & Bien-être": [
        "Le bonheur peut-il s'apprendre ?",
        "Faut-il rembourser la psychothérapie ?",
        "La solitude est-elle choisie ou subie ?",
        "Les réseaux sociaux rendent-ils dépressifs ?",
        "Faut-il travailler pour se réaliser ?",
        "L'amour dure-t-il toujours ?",
        "Peut-on guérir d'un traumatisme ?",
        "La méditation est-elle une mode ou une nécessité ?",
        "Faut-il parler de la mort aux enfants ?",
        "Le stress est-il inévitable dans la société moderne ?",
        "L'échec est-il formateur ?",
        "Faut-il accepter ses limites ?",
        "La jalousie est-elle naturelle ?",
        "Peut-on être ami avec son ex ?",
        "Le perfectionnisme est-il une qualité ou un défaut ?",
        "Faut-il exprimer ses émotions au travail ?",
        "La confiance en soi s'apprend-elle ?",
        "L'empathie est-elle une force ou une faiblesse ?",
        "Peut-on aimer sans souffrir ?",
        "Faut-il consulter un psy ?",
    ],
}


def get_all_topics() -> list:
    """Retourne tous les sujets avec leur catégorie."""
    result = []
    for category, topics in TOPICS.items():
        for topic in topics:
            result.append({"category": category, "topic": topic})
    return result


def get_topics_by_category(category: str) -> list:
    """Retourne les sujets d'une catégorie."""
    return TOPICS.get(category, [])


def get_categories() -> list:
    """Retourne toutes les catégories."""
    return list(TOPICS.keys())


def get_random_topic() -> dict:
    """Retourne un sujet aléatoire."""
    import random
    all_topics = get_all_topics()
    return random.choice(all_topics)
